name: GABDPractica2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - ipykernel
    - git+https://github.com/Oriolrt/GABDConnect
    - ucimlrepo
  - pymongo
  - sshtunnel
  - scikit-learn
  - tqdm
  - matplotlib
  - pandas



